[package]
name = "drip-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
rand = { version = "0.8", features = ["small_rng"] }
futures = "0.3.31"
